AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
